apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: default
spec:
  - name: cassandra
    port: 7000
    targetPort: 7000
  selector:
    app: cassandra

---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: cassandra
  namespace: default
spec:
  serviceName: cassandra
  selector:
    matchLabels:
      app: cassandra
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      serviceAccount: cassandra
      securityContext:
         runAsUser: 1000
      containers:
        - name: cassandra
          image: bitnami/cassandra:latest
          securityContext:
            runAsUser: 1000
          ports:
            - containerPort: 7000
              name: intra-node
          env:
            - name: CASSANDRA_SEEDS
              value: cassandra-0.cassandra.cassandra.svc.cluster.local
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra/data
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 10Gi
